### ISSUE TITLE
Major Wound causes token to be uninteractable

### ISSUE THREAD

**Issue by frondeus** [HavlockV/CoC7-FoundryVTT#962]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

When Major Wound is present, the token cannot be hovered, moved, or interacted in any way.
Foundry returns an error in the console:
```
Error: Invalid BaseTexture systems/CoC7/assets/icons/arm-sling.svg

loadTexture https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:35749
    _drawEffect https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:45401
    drawEffects https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:45358
    draw https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:45016
    promises https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:19710
    map https://frondeus-masks.eu.forge-vtt.com/common/utils/collection.mjs:145
    draw https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:19709
    draw https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:17676
    view https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:15619
    _onClickScene https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:29063
    jQuery 9
    activateListeners https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:28967
    _render https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:2077
    _render https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:28871
    render https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:2011
    render https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:28864
    initializeUI https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:4485
    setupGame https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:4384
    _initializeGameView https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:5213
    _initializeView https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:5189
    initialize https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:4286
    async* https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:53613
    async* https://frondeus-masks.eu.forge-vtt.com/scripts/foundry.js:53595
```
Besides that, the token never displays a Major Wound condition icon.
    
I tested it on latest foundry (0.8.9) and CoC7 (pre-released version, 0.7.2 + everything up to the commit `72eaf44441e62c5de3d1349e6c981718b66ad8fe`). All modules were disabled.
    
When I remove Major Wound, the problem disappears.

**Comment by joaovscorreia** [comment]
@snap01 do you think this is resolved by your #981?

**Comment by snap01** [comment]
Which operating system and web browser / Electron are you seeing this error under?

**Comment by frondeus** [comment]
@snap01 - First of all sorry for the late response.

The problem seems to be resolved, I can hover, interact with the token after I bumped Foundry to V9 and CoC7 to the latest available version (0.7.3).

The Error about the requested texture still exists, and the icon next to the token is replaced by a triangle with an exclamation mark. But I guess this is another issue. Should I create it then?

Answering your question, I'm using Windows 10 with latest chrome as well as Arch Linux with latest Firefox. Before the upgrade I could reproduce a bug on both machines.

**Comment by snap01** [comment]
Thanks for the extra information, this is resolved by #1024
